# Generated by Django 2.0.5 on 2018-07-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180523_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='userbirth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='useremail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.TextField(),
        ),
    ]
