# Generated by Django 2.0.5 on 2018-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qt', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Drinks',
            },
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qt', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('useremail', models.EmailField(blank=True, max_length=100)),
                ('userbirth', models.DateField()),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('user_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qt', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('datetime', models.DateField()),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
