# Generated by Django 2.0.5 on 2018-07-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user_email',
        ),
        migrations.AddField(
            model_name='orders',
            name='datetime',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
